### ISSUE TITLE
Extraction of PKG files

### ISSUE THREAD

**Issue by TanukiSharp** [mhvuze/WorldChunkTool#5]
Hello Vuze,

I have a question regarding the extraction of the PKG files. When I look at the code, it looks like the files should be messed up, so there is probably something I'm missing.

The reference commit for this conversation is 98b92b13820cfacabd928c994f72a70d20e0d698.

In file `Chunk.cs` from line 53 to 55:
```
byte[] ChunkCompressed = Reader.ReadBytes((int)Entry.Value); // Unsafe cast
byte[] ChunkDecompressed = Utils.Decompress(ChunkCompressed, ChunkCompressed.Length, 0x40000);
Writer.Write(ChunkDecompressed);
```

Line 53, you read a meta chunk, let's take the 76th meta chunk of the file `chunk0.bin` as an example, which is 681'474 bytes long, then at line 54 you decompress up to a maximum of 262'144 bytes, which you write to the output file at line 55, and then move on to the next meta chunk.

Where are the missing 419'330 bytes for that meta chunk ?

**Comment by mhvuze** [comment]
Hey,

it's been a while since I did the research on the format (way earlier than the PC release based on the PS4 version of the game), so I don't exactly recall what made me determine 0x40000 as the target unpack size for the chunks -- I could have been plain wrong based on the first few. However - apart from the issue with zero-size chunks - I haven't had any complaints and never ran into any issues personally.

I'll look into it. Let me know if you happen to figure something out along the way by chance.

**Comment by mhvuze** [comment]
As I somehow suspected, it was a bug in reading the size meta data. 0x40000 is indeed the correct unpack size, the code just read beyond the actual compressed file data (search for the header of chunk 77 in 76 for example) The decompressed output was unaffected by that. Thanks for bringing this to my attention, I'll push the minor fix in a minute.

**Comment by TanukiSharp** [comment]
OK if this is a wrong value of the meta chunk size, then it all makes sense.
Thanks for clarifying and the future fix ;)
